### ISSUE TITLE
404 errors caused by trim on base URL

### ISSUE THREAD

**Issue by mwhardesty** [mautic/mautic-wordpress#10]
I have set my base url (http://example.com/lift) in the plugin settings.

However, the form doesn't appear. When I open the console, I see 404 errors. 
It seems that something is stripping out the "t" in the word lift. I tried following it with a slash (http://example.com/lift/) to no effect. 

My input: http://example.com/lift
Plugin form output:
GET http://example.com/lif/form/generate.js?id=1 404 (Not Found)
GET http://example.com/lif/mtracking.gif?d=YTo0OntzOjU6InRpdGxlIjtzOjEzOiJMaWZ0I…Jlc291cmNlcyUyRnVwdGljYXMtdWx0aW1hdGUtZW1haWwtY2hlYXQtc2hlZXQlMkZsaWZ0Ijt9 404 (Not Found)

Note the 't' missing from the URL. 

I wonder if it would be easier to skip the trim and just add some instructions next to the field on the settings page that tell people how it should appear? 

Really looking forward to using this plugin...
-M

**Comment by escopecz** [comment]
Thanks for the report. It was already reported in https://github.com/mautic/mautic-wordpress/issues/7 and the suggested fix is in https://github.com/mautic/mautic-wordpress/pull/9. Could you test the changed code and comment below the pull request if it works for you?

**Comment by mwhardesty** [comment]
Whoops, didn't see that commit. I updated the file you suggested and the form appears. Thanks.
