### ISSUE TITLE
Tag shortcodes do not respect GDPR Tracking script will not be loaded option

### ISSUE THREAD

**Issue by Plato39** [mautic/mautic-wordpress#105]
When using shortcodes the mautic tracking cookie are still loaded - even though the Tracking script location option is set to the first option:

 _'Tracking script will not be loaded when rendering the page; this means that Mautic tracking capability is disabled but you can still use shortcodes to embed Mautic dynamic contents. Use this option to comply with GDPR regulation rules, then load the script by yourself if user accepted tracking.'_

The cookies are:

mautic_device_id
mtc_id
mtc_sid

How can the plugin be configured not to do this?

Thanks

**Comment by shulard** [comment]
Hello,

What's your Mautic version ?

Do you mean that when a page doesn't contains any shortcode, the cookie is not set but whenever a shortcode is used a cookie is generated ?

**Comment by Plato39** [comment]
Hi

The second case - whenever a shortcode is used a cookie is generated.  I'm using Mautic 3.1.0. Using a Mautic tracking gif without the WordPress plugin also creates cookies so I think this is just Mautic behaviour rather than a bug.  I use a GDPR plugin to wrap scripts in a blocker that prevents cookies being set unless consent is explicitly given. I've found this wrapping / blocking can also be applied to a Mautic tracking pixel.

Perhaps you could just update the plugin admin pane warning that tracking pixels are not blocked? Or maybe the shortcode documentation?

**Comment by shulard** [comment]
Hello,

Yep you are right, loading any resource from Mautic will create tracking cookies. I'll update the description to avoid confusion on that point.

**Comment by Plato39** [comment]
Great.

Incidentally, to make mautic tags only load with cookie consent I had to use a javascript version of the tracking gif. The img tag version cannot be controlled with script blocking plugins:

<script>
var mauticUrl = 'https://mautic-root';
var src = mauticUrl + '/mtracking.gif?tags=tag1,tag2,-tag3';
var img = document.createElement('img');
img.style.width  = '1px';
img.style.height  = '1px';
img.style.display = 'none';
img.src = src;
var body = document.getElementsByTagName('body')[0];
body.appendChild(img);
</script>

**Comment by shulard** [comment]
Absolutely, I'll update the description for the tracking pixel too by mentioning this issue.

**Comment by shulard** [comment]
This was fixed in the #106 PR. The text was updated for tracking pixel too, check 4d52b170d688346aeec784a8c6c94ef5a6adf37a for review.
