### ISSUE TITLE
Tracking pixel makes white space below content 

### ISSUE THREAD

**Issue by thusmann** [mautic/mautic-wordpress#108]
It seems like this is happening again: #4 
The display:none style seems to be gone in v3.1.2

**Comment by shulard** [comment]
Hello @thusmann !

The `display:none;` is still available in the source code at: https://github.com/mautic/mautic-wordpress/blob/master/wpmautic.php#L194

Where have you encountered this behaviour ? Which version of Mautic / Mautic Plugin / WordPress ?

**Comment by thusmann** [comment]
Hi @shulard

Thank you for you quick response. Please find the requested information below:
- Mautic Version v3.1.2
- WP Mautic Plugin Version 2.4.0
- Wordpress Version 5.5.3
- Theme Twenty Twenty Version 1.5

See here as an example after the Komoot iframe and before the tags.: https://www.uezgi.ch/2020/11/09/via-ostflanke-auf-den-uetliberg/ 
I used the short code [mautic type="tags" values="wandern"] and it seems to add the tracking pixel.

**Comment by shulard** [comment]
Hello @thusmann !

I finally found some time to take a look at your issue. I've just release the v2.4.2 Plugin release (on GitHub and WordPress.org). I added missing style on the shortcode embedded image. Can you try it ?

I close this issue which seems fixed for me now. If you still have trouble with the latest updated, reopen it and add a comment with the details.
