### ISSUE TITLE
tracking logged in users. Question

### ISSUE THREAD

**Issue by benjaminholloway** [mautic/mautic-wordpress#110]
Question 1:
I was hoping to use this on a wordpress site that already has users registered with it. The WP mautic app has a button to track users that are logged in but it doesnt seem to link up the user in my wordpress database to the mautic instance. Should it? can it? can it get the info from my wordpress database/ wordpress site and link it to there ip? 

Question 2:
Is there a way to get the users info from the log in page, I see in the details I can use a form to get the users info but i dont want to use a form and a log in page. 

thanks for the help in advance.

**Comment by shulard** [comment]
Hello !

If you want to track user specific data, you'll need to override/adapt the plugin behaviour with the `wpmautic_tracking_attributes` filter.
However, by default, this plugin will send new fields to Mautic related to your WordPress instance.

You can take a look here: https://github.com/mautic/mautic-wordpress/blob/a881d68863102730682d649e31066b283d34bb33/wpmautic.php#L264

You need to register new fields in Mautic `wp_user`, `wp_alias`, `wp_registration_date` to retrieve the values (if the fields doesn't exists, data are discarded.

I don't really understand your question 2. What do you mean by "info from the log in page" ?

**Comment by benjaminholloway** [comment]
Thank you for your reply, I am working through that now. With regard to my second question; I have a commerce site, so I dont have a form to grab users data, I have a login page. I was hoping to track a users ip prior to logging in then assigning that ip to the username some how later. 
Again thanks for the above information.
