### ISSUE TITLE
How to add utm_tags in Mautic events

### ISSUE THREAD

**Issue by CATS70** [mautic/mautic-wordpress#113]
Hello,

I would like to add utm_tags in Mautic events (prior to the form submit). I guess it is the purpose of the wpmautic_tracking_attributes filter, but I don't see a place in the wordpress extension settings page to use it. What am I suppoded to do to achieve it?
Thanks

**Comment by shulard** [comment]
Hello @CATS70 !

The `wpmautic_tracking_attributes` filter is here to add details before the tracking event is sent to Mautic. When I talk about tracking event it's not related to Form, only related to the page view event.

So if you want to pass custom fields within your form to Mautic I don't know how to do it...

Maybe I misunderstood your issue, if you want to add details to the mautic tracking event, you must add a piece of code like this in a plugin / theme : 

```php
add_filter('wpmautic_tracking_attributes', function($attrs) {
    $attrs['utm_tags'] = $_REQUEST['utm_tags'];
    return $attrs;
});
```
