### ISSUE TITLE
Mautic merges Wordpress Users

### ISSUE THREAD

**Issue by Onkelschlag** [mautic/mautic-wordpress#117]
Hey there,

i have two users with different emails in wordpress. But mautic merges everytime the two users to one contact. 
Only the email field in mautic is the identifying field. 
i log in as the user A the contactdetails are updated in Mautic to user A when a log in as user B Mautic does not generate a new user but updates the contact details from user A to user B. 

cheers

**Comment by Onkelschlag** [comment]
Tried to solve the problem with the custom attribute handling. I can parse the wp_user_id to mautic. This field is set in mautic to be the identifying field with the email field. But the problem is still there. 
in the tracking features in mautic i turned off tracking the ip adresses. 
any ideas of help would be great! 

Thank you.

**Comment by shulard** [comment]
Hello !

I'm not sure I can help you here because it seems to be a Mautic integration issue. I'm not a Mautic power user, I'm just aware of some technical details to talk with the API. I suggest that you ask the question in the Mautic forum or slack, more advanced users may have already resolved this issue (in WordPress or somewhere else).

If you have more technical details about this issue I may take a look at how it can be related to this WP plugin...

**Comment by Onkelschlag** [comment]
Hey @shulard thanks for your reply. Actually i found something in the forum. This is exactly my Problem. But it is from 2016! 
There must be a Problem because mautic still merges different wp users with the same ip adresses as one user in mautic. 

https://forum.mautic.org/t/tracking-users-of-wordpress-from-the-same-ip/3438

**Comment by Onkelschlag** [comment]
@shulard could you do me a favour and just check für me if the Mautic behaviour is the same. 
1. use the Mautic Wordpress Plugin
2. Track loggedin users
3. Make to test users in Wordpress UserA and UserB which are not synched to Mautic
4. Log in as UserA and check if Mautic has generated a new contact with the Info of UserA
5. Now log in as UserB and check if Mautic has generated a new UserB or has just updated the fields from UserA because Mautic or the Plugin just checks the IP address to identify the User. 

in my mind Mautic should check the IP address and the email field which is an identifier in Mautic. If the Email is the same merge a contact if not generate a UserB and not oh they have the same IP addresses lets merge the contact. 

Hope this is more technical info to check the behaviour. 
My tracking settings in Mautic are only anonymize the ip addresses. The rest is turned off. 

Thanks for your help. I would really appreciate if you could check this on your side.

**Comment by Onkelschlag** [comment]
Another test from my side.
A logged in Wordpress via my smartphone and Mautic has now generated two identicall users. This can‘t be the right. The same email, the same name…but different device logs.
