### ISSUE TITLE
Mautic redirecting to Mautic Login Page when click in a form field

### ISSUE THREAD

**Issue by AlexFelicioni** [mautic/mautic-wordpress#120]
Hi every body.
I have the followed issue.
When i make a click in Mautic form field to fill it, i am redirected to Mautic login page and i can not fill the form.
I am using Mautic  stable release 4.2.0, wordpress release 5.9.1, WPMautic plugin release 2.4.2 and PHP version 7.4.
Any body can help me?

**Comment by RCheesley** [comment]
Hi @AlexFelicioni please post your request at https://forum.mautic.org/c/support where you will be much more likely to get more people able to assist you.
