### ISSUE TITLE
Mautic does not apply Themes

### ISSUE THREAD

**Issue by AlexFelicioni** [mautic/mautic-wordpress#121]
Hi every body.
I have the followed issue.
Mautic does not apply themes in forms and Landing Pages. In Landing pages constructions, its availabe only blank theme, but all defaults themes are instaled. Any budy cam help me?
I am using Mautic stable release 4.2.0, wordpress release 5.9.1, WPMautic plugin release 2.4.2 and PHP version 7.4.
Any body can help me?

**Comment by RCheesley** [comment]
Hi @AlexFelicioni please post your request at https://forum.mautic.org/c/support where you will be much more likely to get more people able to assist you.
