### ISSUE TITLE
Despite https being setup, forms are sent via http post

### ISSUE THREAD

**Issue by fhamborg** [mautic/mautic-wordpress#126]
I setup mautic with https, both in the WP Mautic plugin and Mautic itself (see screenshots):

<img width="245" alt="grafik" src="https://github.com/mautic/mautic-wordpress/assets/18700166/22d970b8-b7df-40cf-9da3-a389e31b65d5">

<img width="439" alt="grafik" src="https://github.com/mautic/mautic-wordpress/assets/18700166/9c5910d7-e92a-4437-80c1-8e7ed884da58">

The form is also displayed properly, but when I hit the Submit button, I get this error:

<img width="619" alt="grafik" src="https://github.com/mautic/mautic-wordpress/assets/18700166/eb43ae67-6e2d-4219-a5d9-89b9ea838e69">

Reason seems to be that the post request is sent to the http address instead of https (despite other requests are made via https), as configured:

<img width="1301" alt="grafik" src="https://github.com/mautic/mautic-wordpress/assets/18700166/9961c218-b790-4afc-9d09-82ccfeeb7859">

**Comment by RCheesley** [comment]
Hi there, please post your issue over at https://forum.mautic.org/c/support as Github is for reporting bugs with Mautic whereas the forums are for getting help if you encounter problems :)

**Comment by fhamborg** [comment]
Thanks mate! :)

**Comment by utiq** [comment]
@fhamborg how did you solve the issue? I'm having the same problem
