### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by komitaltrade** [mautic/mautic-wordpress#15]
As more I search, more I like Mautic concept. But .....

Is it some particular reason why Mautic don't have multiple Mailbox possibilities (like OROCRM)?

It is not about the issue that Mautic should not to be "girl for everything", it is that I see at least several downsides (vs marketing):
- another tracking channel (as well visual option for dashboard)
- "branding campaigns" (ie) ios9@pinapple.com, iphone6s@pinapple.com (looks much more interesting/atractive to launch campaign with = email prefix, isn't?)
- Subscription is not a Mautic task (on first look), but tracking news@pinapple.com during (ie) ios9 campaign (separated from ios9@pinapple.com actions) can show mutual impact on two complete different actions.

**Comment by escopecz** [comment]
Just a side note, this is issue/feature tracker for Mautic - Wordpress plugin. If you'd like a discussion about a topic, I'd recommend the community forum:

https://www.mautic.org/community

If you'd like to create an official feature request for Mautic, use:

https://github.com/mautic/mautic/issues

**Comment by shulard** [comment]
Hello @komitaltrade,

Have you posted a topic in community forum ? If so, please can you add the link here to complete that issue ?

I just close the issue here because it's a really old one and because it seems to be "fixed".
