### ISSUE TITLE
404 Error in form script due to index.php mod_rewrite rule

### ISSUE THREAD

**Issue by ramielbarsoum** [mautic/mautic-wordpress#16]
Is there a way to remove the index.php in the mautic URL?
The mautic wordpress plugin, form script src references my mautic install without the index.php in the src, where as the automatic script calls for it.

Example:
Automatic script:
`<script type="text/javascript" src="http://mautic.example.com/index.php/form/generate.js?id=1"></script>`

Wordpress plugin script:
`<script src="http://mautic.example.com/form/generate.js?id=1" type="text/javascript"></script>`
Leading to a 404 file not found error.

Any advice on the best way to fix this while also allowing the main dashboard to be accessible?
http://mautic.example.com/index.php/s/dashboard

**Comment by escopecz** [comment]
Mautic has rules for rewriting the `index.php` from every URL in the *.htaccess* file. Make sure your server is configured properly to support this file.

**Comment by ramielbarsoum** [comment]
Being that the default values of the included .htaccess file and the default of the wordpress plugins are different in their rewrite rules, is it possible to recommend the necessary changes in the plugin docs?

**Comment by escopecz** [comment]
I'm not sure I follow. The plugin and Mautic and its documentation are opensource so you are welcome to recommend any changes via a pull request.

**Comment by ramielbarsoum** [comment]
Thank you @escopecz I was looking for any recommendations on what the best way to update the .htaccess in order to allow both the plugin and the mautic installations to both be reachable.

I do not have enough knowledge at this moment on what the best way to do that, and was hoping that any recommendations here could potentially help others that may run into the same 404 error with their plugin installation.

If this is not the recommended place for this I apologize. I can seek further recommendation in the mautic community forums.

Thank you for your reply, time and energy.

**Comment by ramielbarsoum** [comment]
I realized that my first comment was not showing the script output as It gets edited out, I edited to show the script output to clarify.

**Comment by escopecz** [comment]
Why would you update the .htaccess file? The file is ready to use. You just have to allow it on your server (which is allowed by default on majority of hostings). It depends on your server OS how to allow it, so google for it. Here is one tutorial where you can read more information:

https://www.digitalocean.com/community/tutorials/how-to-use-the-htaccess-file

BTW, if you use ngnix, it has uses a different file than .htaccess. There are some articles and discussions about it.

**Comment by ramielbarsoum** [comment]
Hi @escopecz , I already am using the .htaccess file and have mod_rewrite enabled.
The issue for me seems to be that the WP-Mautic plugin, when using the form shortcode, results in a script, who's source, does not include the index.php portion of the URL. where as in the default Mautic .htaccess, the rewrite rules, at least based on my default installation, reference the index.php in the src URL.
So to clarify as mentioned previously:

The Automatic Form script as given by Mautic installation:
`<script type="text/javascript" src="http://mautic.example.com/index.php/form/generate.js?id=1"></script>`

The Mautic Wordpress plugin script output:
`<script src="https://mautic.example.com/form/generate.js?id=1" type="text/javascript"></script>`

As you can see, the wordpress plugin output does not include the index.php as referenced in my Mautic installation embed code.

**Comment by escopecz** [comment]
If Mautic uses `index.php` in its URL, then .htaccess or mod_rewrite doesn't work!

On the other hand, you know that you are the one who configured Mautic - WP plugin, right? You've inserted the Mautic base URL without the `index.php` part. But it is not the proper fix to add it to the Mautic base URL. Configure the .htaccess or mod_rewrite or whatever it is that is forbidding Mautic to use the nice URLs.

**Comment by ramielbarsoum** [comment]
I understand now what you are trying to refer me to @escopecz.
I double checked my virtual files and discovered an error in my directory entry.
Now I am getting the mtracking.gif to show up, the form is loading, as well as no index.php is being called in my mautic URL.

Thank you for your patience and willingness to reply. Your comments helped check my installation again and helped me resolve my issue. deep gratitude.
