### ISSUE TITLE
Get data from other forms

### ISSUE THREAD

**Issue by bobwol** [mautic/mautic-wordpress#19]
It could be interesting if Mautic could get data from other forms (forms created by Gravity Forms or forms created on the theme, like a simple contact form). 
I know the LeadIn plugin does that and it's awesome. It uses the same pixel tracking like Mautic, but also reads any <input type="text / email" > element.

Make sense?

**Comment by SvetZitrka** [comment]
Lead time we have used and I agree that you do for Mautic could be very useful.

**Comment by naomicbush** [comment]
@bobwol The [Gravity Forms Mautic Add-On](https://gravityplus.pro/gravity-forms-mautic/) should work for you

**Comment by bobwol** [comment]
Hi @naomicbush !! Thanks for the contribution.
Actually this addon is not ready yet. They are just collecting emails for a waiting list. I'll be waiting news of it.

**Comment by naomicbush** [comment]
@bobwol I'm the developer of the add-on so I happen to know that's not true :-) I wouldn't have posted it here otherwise. 

If you have questions or want accurate information, you should use the contact information available to you on the plugin page.

**Comment by SvetZitrka** [comment]
I already use a plugin yet satisfied

**Comment by shulard** [comment]
Hello @SvetZitrka,

Your issue seems to be fixed so I close this one. The idea to track others forms than the Mautic ones is awesome but has to be made for each form builder plugin...
