### ISSUE TITLE
Shortcode / Form Issue

### ISSUE THREAD

**Issue by craigvansant** [mautic/mautic-wordpress#20]
I'm using the hosted solution (1.3.0) on one url ( MarketKeeper.com ) and I have a Wordpress install on another url. ( BeAVendor.com )

Trying to use the shortcode as seen in the text portion of my WP editor  " [mauticform id="1"]  "

I'm using the WP plugin of course.  On my page with the shortcode above 
https://beavendor.com/mautic-test-page/

I do not see my form but in the source code I can see  ...
`<script type="text/javascript" src="http://marketkeeper.com/form/generate.js?id=1"></script>` 

My form appears ok here

http://marketkeeper.com/s/forms/preview/1

Any thoughts?  

Thanks in advance.

**Comment by craigvansant** [comment]
I now understand my challenge.  My domain with the form and the tracking pixel is https .  My install of Mautic was not. https .  The two must match or they get blocked.

**Comment by escopecz** [comment]
Yes, you get it right. If you try to load a http asset to a https website, it will throw an error because the security is violated by that. You should contact the host of your Mautic and ask for SSL certificate for your Mautic. It's not an issue of this plugin.

**Comment by VcDesigns** [comment]
Hello,

I have put together a video to show that the WP plugin works just fine for Mautic. I just went over the problems others have been adding on github and read the primary section on mautic itself and saw the missing piece that isn't explained anywhere.

https://youtu.be/zw5I_x4-7Gc

**Comment by scottbuscemi** [comment]
@VcDesigns please read the issue before spamming all of the open issues.

@escopecz can you please close this issue since it has been resolved?

**Comment by VcDesigns** [comment]
First of all i wasn't spamming anything, and this wasn't closed, it was open.  I simple added a video for those who been having issues with the WP plugin, that isn't spamming that is helping. I see you have no idea what spamming is if you see someone adding a video link for providing help.

**Comment by andreab79** [comment]
hi, i have the same problem, not shows mautic form in wordpress. both have ssl and plugin is correctly installed. inspection the wp page i see code 

<script type="text/javascript" src="https://hotelnordik.marketingagile.it/form/generate.js?id=3"></script>

but page is empty, without form

**Comment by andreab79** [comment]
solved, issue was related to https but form was not shown for my hosting cache service
