### ISSUE TITLE
Shortcode in Widgets

### ISSUE THREAD

**Issue by erikpixel** [mautic/mautic-wordpress#21]
It'll be awesome, if we can make the form shortcode, work in Text Widgets!

Today if you add a form with the plugin Form in Widget, he doesn't show the form;

**Comment by VcDesigns** [comment]
Hello,

I have put together a video to show that the WP plugin works just fine for Mautic. I just went over the problems others have been adding on github and read the primary section on mautic itself and saw the missing piece that isn't explained anywhere.

https://youtu.be/zw5I_x4-7Gc

**Comment by shulard** [comment]
Hello @erikpixel,

Is your issue fixed using the youtube video ?

For the moment I close that issue because it's an old one, if you still have a problem please reopen it !

**Comment by VcDesigns** [comment]
i didn't have a problem with this i placed a video helping those who had problems.  You can close this

**Comment by shulard** [comment]
And thank you very much for that video, it helps a lot to understand the plugin behaviour.
