### ISSUE TITLE
ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by ghost** [mautic/mautic-wordpress#26]
I have a wordpress blog and a mautic free account in matic.net.
When I use the shortcode nothing appears on the blog and I get this error message ERR_BLOCKED_BY_CLIENT.
My blog use http and the mautic.net uses https but I put both http and https on the base url of the plugin pointing to my account on mautic.
What am I doing wrong?

**Comment by shulard** [comment]
Hello,

Is this issue still valid ? Is so, can you give me more details about the `ERR_BLOCKED_BY_CLIENT` error ? What's the page URL ? What's the URL which is actually blocked ? Where your blog is hosted ?

**Comment by shulard** [comment]
Since the user is not active anymore on Github, I close this issue which was surely about CORS settings.
