### ISSUE TITLE
Javascript Location

### ISSUE THREAD

**Issue by MxyzptlkFishStix** [mautic/mautic-wordpress#31]
Would it be possible to create an option to place the javascript code before the closing body tag?

**Comment by BurlesonBrad** [comment]
@MxyzptlkFishStix : Give this a whirl

```
<?php
add_action('wp_footer', 'add_stix');

function add_stix() { ?>

// This is where you'd paste your stix | your fish | your xyz | and your js code //

<?php } ?>
```
post back and close #31 if that works. if it does **not** _(which, it should)_ then please post back as well and let me know that it didn't work for 'ya 
:sunglasses: Cool? :sunglasses:

**Comment by shulard** [comment]
Hello @MxyzptlkFishStix,

Thank you for the report, I'll work on it 😄.

**Comment by shulard** [comment]
Hello @MxyzptlkFishStix,

I've just merged the ability to inject script in footer 😄.
You can download the latest version (v0.2.0) to use it !

https://github.com/mautic/mautic-wordpress/releases/tag/v0.2.0
