### ISSUE TITLE
Setup with WordPress

### ISSUE THREAD

**Issue by trevorjwood** [mautic/mautic-wordpress#36]
I've probably done something wrong, but I'm not seeing the tracking JavaScript after installing and setting up the mautic plugin on my WordPress site.

The only reference to Mautic that I'm seeing is 

<img style="display:none" src="https://networkmidlands.mautic.net/mtracking.gif?d=LaLaLa string of letters" alt="mautic is open source marketing automation" />

There's no sign of the script anywhere. What am I doing wrong?

**Comment by zenzozen** [comment]
same here. i only see the image tracking, but no script

**Comment by trevorjwood** [comment]
It seems that it's working anyway - not sure how but I'm getting stuff added to Mautic and the Contact Form 7 integration is working

**Comment by VcDesigns** [comment]
Hello,

I have put together a video to show that the WP plugin works just fine for Mautic. I just went over the problems others have been adding on github and read the primary section on mautic itself and saw the missing piece that isn't explained anywhere. 

https://youtu.be/zw5I_x4-7Gc

**Comment by shulard** [comment]
Hello @trevorjwood, @zenzozen,

Has the video helped you to fix your problem ?

**Comment by trevorjwood** [comment]
seems to be working
