### ISSUE TITLE
Compatibility Wordpress 4.6

### ISSUE THREAD

**Issue by eth4ever** [mautic/mautic-wordpress#37]
The plugin doesn't seem to be compatible with WP 4.6.

After installing and activating the plugin this error appears:

> Parse error: syntax error, unexpected '[' in /home/sites/site46280/web/wp-content/plugins/wp-mautic-form-integrator/wp-mautic-form-integrator.php on line 982

**Comment by escopecz** [comment]
I think you are using different WP plugin. This plugin doesn't contain any `wp-mautic-form-integrator/wp-mautic-form-integrator.php` file.

But my guess is you need just PHP 5.4+ to run it.
