### ISSUE TITLE
Bump version and update the official WordPress plugin repository

### ISSUE THREAD

**Issue by alfiehub** [mautic/mautic-wordpress#38]
Link to plugin:
https://wordpress.org/plugins/wp-mautic/

> Version 1.0.1
> Last Updated: 1 year ago

The plugin has been updated since then, but the version number has not been bumped.

The WordPress plugin repository hasnt been updated either, possibly because of this very reason.

After downloading the plugin directly from this repository, the JS is used instead of the .gif tracking pixel directly, so it's clear that the plugin hosted at WordPress is outdated.

Similar issue:
#36

**Comment by Arjoni** [comment]
Yeah the plugin should be updated. Many confusions with the versioning.

**Comment by wittwerch** [comment]
Can you please release a new version?

**Comment by shulard** [comment]
Hello,

I'm going to work on that release process to automate it between Github and WordPress.org.
If you want to take a look at the update: #44 

I close that issue in profit of the #44.
