### ISSUE TITLE
does not use https scheme

### ISSUE THREAD

**Issue by jbmanos** [mautic/mautic-wordpress#39]
despite having the correct scheme in the options panel, the script still loads http and gets blocked because the site and the mautic dashboard are https

not sure how to make the plugin specify https schemes

**Comment by jbmanos** [comment]
I should clarify:  it appears that the plugin works and loads the mautic.js, but the mautic.js has the wrong scheme in it, even though I access the mautic dashboard over https, and the base url in configuration has https specified.

**Comment by jbmanos** [comment]
solved my own problem...   turns out that I had to add this to the htaccess:

`SetEnvIf` `x-forwarded-proto https HTTPS=on`

**Comment by joeyparis** [comment]
@jbmanos Did you need to add this to your mautic installation or your wordpress site?
