### ISSUE TITLE
Tracking pixel makes a white space below website theme

### ISSUE THREAD

**Issue by lance-spurgeon** [mautic/mautic-wordpress#4]
because the tracking pixel in theory is just calling an image the pixel makes spacing at the footer of the website that is viewable from the front end. if the wordpress pixel could be encased between <pre>&lt;noscript&gt;&lt;/noscript&gt;</pre> tags it would hide this from the frontend

**Comment by escopecz** [comment]
Thanks for your report. 

I just tested your solution. It will not load the tracking image in browsers which has javascript allowed. Which is almost 100% these days. If the image is not loaded then Mautic doesn't know about page hit.

But I guess the `style="display:none"` could solve the problem. I'll commit this change.

**Comment by pedrommone** [comment]
Its worked very well, but you forgot to update it on WordPress plugins repository.

**Comment by escopecz** [comment]
Updated. Thanks for reminder

**Comment by shulard** [comment]
Since this was fixed, I close this issue.
