### ISSUE TITLE
Dwell time not recording

### ISSUE THREAD

**Issue by jbmanos** [mautic/mautic-wordpress#40]
I'm not sure how to troubleshoot this.   
I had the WP repository version installed on a WP 4.7.1 (php7) and the tracking gif was working and recording page visits and dwell times.

I switched to this version and the script is loading and it records page visits, but now I am seeing 0 seconds for the average time spent on site.  

The script is loading, and the client loads the mtracking.gif, but for some reason, now I'm not getting the time spent on the site.

How can I troubleshoot this?

**Comment by shulard** [comment]
Hello @jbmanos,

Is this issue still valid ?
Maybe it's related to a Mautic update ? What's the page URL where DWell time is not recording anymore ?

**Comment by shulard** [comment]
Hello !

We are going to publish a new release of the wordpress plugin on WordPress.org asap. The latest changes are in beta and can be tested using the following ZIP : https://downloads.wordpress.org/plugin/wp-mautic.zip

We have added a whole test suite to ensure that shortcode behave correctly : https://github.com/mautic/mautic-wordpress/blob/master/tests/ShortCodeTest.php

If you still encounter the problem, please give feedback on this latest version here : https://mautic.slack.com/archives/C0DJ82PFF/p1496154940234602
