### ISSUE TITLE
[META] Define an automatic way to deploy plugin code to WordPress repository.

### ISSUE THREAD

**Issue by shulard** [mautic/mautic-wordpress#44]
Hello,

Since the plugin is hosted on Github, I think it can be awesome to have an automatic process to push new changes to WP plugin repository.

I'll update this issue with details about this, if you have any feedback just tell me here 😄 !

**Comment by shulard** [comment]
Linked to #24

**Comment by shulard** [comment]
Hello @escopecz,

Can you give me the details about the WordPress.org SVN repository for this plugin ?

**Comment by shulard** [comment]
Using some unit tests can be very useful as well, need to check the "Automated Testing" handbook: https://make.wordpress.org/core/handbook/testing/automated-testing/

**Comment by shulard** [comment]
Also using TravisCI as a build pipeline can be a nice improvement to encore project quality.

**Comment by shulard** [comment]
Now, the project use PHPCS rules : #45

**Comment by shulard** [comment]
Hello @escopecz,

I don't if you are the right person, but can you activate TravisCI builds on this repository ? 

I've added a new branch to start implementing unit tests and I need them to be run on every push :smile:.

You can check here : https://travis-ci.org/mautic/mautic-wordpress

**Comment by escopecz** [comment]
Thanks for all the work! I think I managed to do that.

**Comment by shulard** [comment]
@escopecz, thank you, the first build was triggered 👍.

https://travis-ci.org/mautic/mautic-wordpress/builds/232043199

I think that the next step will be to publish a new plugin version on the WP plugin repository.

**Comment by shulard** [comment]
Hello @escopecz,

I've worked today on the unit test suite to ensure plugin stability...
We now have about 80% of code coverage and the build is green 😄.

Any news about the wordpress SVN credentials ? Is it something that you can share ?

**Comment by escopecz** [comment]
We are considering Scrutinizer at the moment. Write me on Slack (@john) for the credentials. It's a topic for private discussion ;)

**Comment by shulard** [comment]
I close the issue here since I have collected all the required things.
