### ISSUE TITLE
Mautic Tracking Pixel <script> block shows at top of page

### ISSUE THREAD

**Issue by kalegood** [mautic/mautic-wordpress#48]
When using latest WP Mautic from git, the <script> block calling the tracking pixel shows as text at top of page. 

This doesn't happen with the install from Wordpress's interface.

**Comment by shulard** [comment]
Hello !

Which version of WordPress / PHP are you using ? How are you installing the plugin ?

**Comment by HectorPN** [comment]
Same here.

WP 4.7.5
PHP 7.1.5

Downloaded the ZIP from Github and uploaded manually.

It outputs the script like this:

`&lt;script&gt;\n    (function(w,d,t,u,n,a,m){w[\'MauticTrackingObject\`

... notice it prints the opening bracket as HTML code and not an actual character.

**Comment by shulard** [comment]
Ok there was an error in the script generation... It should be fixed now with the latest commit.

I've also made some tags because you must avoid using latest master commits in your project, take a look at : https://github.com/mautic/mautic-wordpress/releases

**Comment by HectorPN** [comment]
Thanks Stephane.

When will the last version be available on the WP repo?

**Comment by shulard** [comment]
ASAP... I recently take place in the WP Plugin dev team and I'm still discussing with @escopecz to retrieve WP repo access...

**Comment by HectorPN** [comment]
Cool!

 

So it is safe to deploy your version 0.1.0 from 20 mins ago in production? Or is it still beta?

**Comment by shulard** [comment]
If you previously used the Github version yes it's as safe as your previous install. The script tag issue was introduced in the latest commits but it's now fixed.
