### ISSUE TITLE
Tracking Pixel not working with Thrive Theme

### ISSUE THREAD

**Issue by fuzzyboy15** [mautic/mautic-wordpress#6]
Hi there.

I have a Wordpress site and using Thrive theme on it. I installed the mautic plugin and viewed the page source, and saw that the tracking pixel is indeed found on the site.

I created a simple test campaign in Mautic which goes something like this:
1. Fill-up form
2. Redirect to thank you page
3. Send thank you email once visitor hits the thank you page in step 2.

![github](https://cloud.githubusercontent.com/assets/13650945/9075212/c442e4a8-3b44-11e5-9060-0febdfe83e74.png)

Mautic captured the email address but it did not track the visit to the thank you page....

![ty 0 hit](https://cloud.githubusercontent.com/assets/13650945/9075236/28e18478-3b45-11e5-929a-86fafef4101a.png)

Therefore, thank you email was also not triggered to send....

![send ty 0](https://cloud.githubusercontent.com/assets/13650945/9075243/4248f8ce-3b45-11e5-9204-4758a5d9dd9f.png)

I don't know what I'm missing here.... could this be a conflict between mautic and thrive? Hope you guys could pitch in.

Thank you in advance.

**Comment by MaxOnTheHill** [comment]
I use thrivetheme on sites and tracking works OK ... but did notice on one site somewhere (can't remember if it was a thrive one or not) that the url of the tracking pixel was actually broken for some reason - so it was injecting, but with incorrect url so 404'd.

but am using it successfully on a number of thrivetheme sites .... but not quite setup exactly same as yours ... perhaps I need to have a bit of a test with campaign similar to your one and check - but haven't noticed an issue.

**Comment by fuzzyboy15** [comment]
Hi @MaxOnTheHill 

Thanks, man... would really help if you can test it from your end and see if it works or not. By the way, not sure if this will help but just in case, this is how I inserted my URL in the campaign builder for the "visits thank you page":

![url](https://cloud.githubusercontent.com/assets/13650945/9077410/7aac2996-3b60-11e5-8b4f-8d3bf92ad2c6.png)

**Comment by fuzzyboy15** [comment]
Found the fix.

I disabled the mautic plugin and inserted the tracking pixel manually to my thrive pages.

**Comment by shulard** [comment]
Since this was fixed, I close the issue.
