### ISSUE TITLE
Mautic Focus doesn't work

### ISSUE THREAD

**Issue by Aneta09** [mautic/mautic-wordpress#64]
I had updated plugin Mautic, I tested on Mautic Cloud and self-hosted. The Focus Item (collecting data) when I submit I have information Please wait... You can check here: https://marketer-b2b.pl/focus/  Try to go out from the website.

**Comment by escopecz** [comment]
I'll close this issue because it doesn't follow the predefined template. Please try to create a new one and fill in all the requested information. Also attach the errors from your error log: https://mautic.org/docs/en/tips/troubleshooting.html

**Comment by escopecz** [comment]
Ah, sorry you posted to the wordpress plugin repository. Post the Mautic issues to Mautic repository: https://github.com/mautic/mautic

**Comment by shulard** [comment]
Hello @Aneta09,

I've tested on your page and the focus element is displayed when I leave the page. Maybe it's related to your focus configuration... As @escopecz told you it seems more related to a Mautic issue than a WordPress plugin issue. The plugin is just here to help adding the right script to the right place.
