### ISSUE TITLE
.net domain trimmed

### ISSUE THREAD

**Issue by gdlin** [mautic/mautic-wordpress#7]
Hi, 
I'm using a .net domain, and it's trimmed. if my domain is http://mautic.example.net/ , the pixel image is rendered as http://mautic.example.ne/....  

I removed the **\t** on the trim function's parameters and it worked, but **\t** should remove tabs, not the **_t_** letter. I don't know if it's my php version, but it's a shared hosting so I have no control over that.

**Comment by escopecz** [comment]
Hi, I also thought that `\t` should trim tabs, but it seems it has to be encoded in a different way. I made a similar change as you did to my PR https://github.com/mautic/mautic-wordpress/pull/5. If you could test it and comment how the test went, it'd help to get the PR merged.

**Comment by TiagoRodrigues** [comment]
@escopecz I sent a PR #9 using your PR #5 but rolling back the Trim function adding ``` trim($options['base_url'], " \t\n\r\0\x0B/") ```

As you can see the only difference is the double quote.

**Comment by shulard** [comment]
Fix by #9
