### ISSUE TITLE
Dynamic Web Content not rendering

### ISSUE THREAD

**Issue by arrfonseca** [mautic/mautic-wordpress#72]
Hey! 
Thank you very much for your help and support.

I have this test website in www.thinkevery.com/wpevery

Its wordpress 4.8.4 over php 5.6.31

And I have in auto.thinkevery.com my own install of mautic (2.11.1) over php 7.1

Public pages that you can see the DWC implementation:

Blog post: https://www.thinkevery.com/wpevery/blog/content-draft/
In the sidebar you can see 2 texts: "prueba" which is DWC implemented with shortcode
and "Text in the html - this shows up if the visitor is not known" which is DWC implemented with html div code for the sake of testing

I've also created a post with implementation in the text body at: https://www.thinkevery.com/wpevery/blog/mautic/

also with div and shortcode.

You can see my DWCs here:

<img width="1426" alt="captura de pantalla 2017-12-11 a la s 11 22 39" src="https://user-images.githubusercontent.com/2806773/33845320-b0facf72-de68-11e7-8ab0-653d3c09a40c.png">

They're testing implements and are basically images as you can see here:

<img width="1419" alt="captura de pantalla 2017-12-11 a la s 11 25 51" src="https://user-images.githubusercontent.com/2806773/33845386-eb5bf8ee-de68-11e7-92ad-c1a62045c67e.png">

and here:

<img width="1421" alt="captura de pantalla 2017-12-11 a la s 11 25 18" src="https://user-images.githubusercontent.com/2806773/33845405-f8c57500-de68-11e7-8941-d9137ac7f677.png">

My campaign uses a slot named "prueba" and is configured following youtube tutorial.
Basically all contacts that are in the segment "contact form" (formulario de contacto) are part of the campaign. You can find the contact form here: https://www.thinkevery.com/wpevery/home/contacto/

Please, to create an user to that segment fill up the contact form and leave the checkbox empty, otherwise you're going to other segment (it's our newsletter opt-in).

<img width="444" alt="captura de pantalla 2017-12-11 a la s 12 22 50" src="https://user-images.githubusercontent.com/2806773/33847015-d1fa1d62-de6e-11e7-9e86-539d93bb74c2.png">

<img width="624" alt="captura de pantalla 2017-12-11 a la s 12 28 06" src="https://user-images.githubusercontent.com/2806773/33847038-e0f83cea-de6e-11e7-815a-d95badc289ef.png">

Then I've set up Request Dynamic Content like this:

<img width="608" alt="captura de pantalla 2017-12-11 a la s 12 29 20" src="https://user-images.githubusercontent.com/2806773/33847116-20e48ab6-de6f-11e7-873f-0de40fed709e.png">

As a conditional I've set up just "has a valid email address" just for testing purposes (maybe true email syntax but fake address are affecting the test?). When condition is true than it should show second DWC.

I've checked in the server and images are uploaded correctly at: auto.thinkevery.com/media/images/be668982067e91220d5eabdd926fe6e2.png
and
auto.thinkevery.com/media/images/a23de7ee2a92584e099933a62d5c7b2f.png

Also, I've noticed campaign is triggered to some contacts but no DWC is rendered.
<img width="1045" alt="captura de pantalla 2017-12-11 a la s 12 40 31" src="https://user-images.githubusercontent.com/2806773/33847651-df12d88e-de70-11e7-8801-099a51448af9.png">

Since campaigns and other processes depend on cron jobs and I cannot manually set direct commands into my shared host, so I've set them up using a PHP file you've provided here. Campaigns triggers each 15 minuts so you can trigger them here: http://auto.thinkevery.com/cronjob.php?ILoveMautic (i know this is not safe but i'll change credentials after this or moving into a dedicated host.

Finally, I'd like to mention I'm not a developer but can manage myself some stuff. :)
Appreciate your help! Thanks!
Alessandro

**Comment by arrfonseca** [comment]
Thanks @shulard 

its like this now
<img width="1061" alt="captura de pantalla 2017-12-11 a la s 13 24 41" src="https://user-images.githubusercontent.com/2806773/33849617-bead4470-de76-11e7-8e3a-84da3b7cad30.png">

Does adding https or directories change anything? Want me to test adding those, including WP directories?

Is there a script to directly output a DWC on a webpage for testing purposes?

Thanks!

**Comment by arrfonseca** [comment]
@shulard 
I've added https addresses to the config and tested. Still not rendering. 
Then I've added these lines to the functions.php file of my child theme:

add_filter( 'allowed_http_origins', 'add_allowed_origins' );
function add_allowed_origins( $origins ) {
    $origins[] = 'https://auto.thinkevery.com';
    $origins[] = 'http://auto.thinkevery.com';
    return $origins;
}
Still not rendering

**Comment by arrfonseca** [comment]
dear @shulard 
I could solve the problem thanks that you pointed me to the right direction. CORS must be enabled not only in mautic installation but also in wordpress. To solve that I changed my .htaccess file as follows:

# BEGIN WordPress
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]
</IfModule>

<FilesMatch "\.(php)$">
  <IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
  </IfModule>
</FilesMatch>

# END WordPress

# ##############################################################################
# # CROSS-ORIGIN RESOURCE SHARING (CORS)                                       #
# ##############################################################################

# ------------------------------------------------------------------------------
# | Cross-domain AJAX requests                                                 |
# ------------------------------------------------------------------------------

# Enable cross-origin AJAX requests.
# http://code.google.com/p/html5security/wiki/CrossOriginRequestSecurity
# http://enable-cors.org/

# <IfModule mod_headers.c>
#    Header set Access-Control-Allow-Origin "*"
# </IfModule>


# ------------------------------------------------------------------------------
# | CORS-enabled images                                                        |
# ------------------------------------------------------------------------------

# Send the CORS header for images when browsers request it.
# https://developer.mozilla.org/en/CORS_Enabled_Image
# http://blog.chromium.org/2011/07/using-cross-domain-images-in-webgl-and.html
# http://hacks.mozilla.org/2011/11/using-cors-to-load-webgl-textures-from-cross-domain-images/

<IfModule mod_setenvif.c>
    <IfModule mod_headers.c>
        <FilesMatch "\.(gif|ico|jpe?g|png|svgz?|webp)$">
            SetEnvIf Origin ":" IS_CORS
            Header set Access-Control-Allow-Origin "*" env=IS_CORS
        </FilesMatch>
    </IfModule>
</IfModule>

**Comment by ergu0015** [comment]
Have exactly the same problem. Can I do a copy/paste for my own htcaccess or is there any unique values? Couldn't find any...

**Comment by shulard** [comment]
Hello @ergu0015,

Can you create a new issue ?
Also, can you gave me access to the webpage where the dynamic content failed to render ? and add all the details you have about your configuration (mautic white listed domains, htaccess...).

Since multiple peoples have the same problems with CORS, I'll check to add a piece of doc or a verification tool inside the plugin...

**Comment by arrfonseca** [comment]
@ergu0015 above I copied the exact same code in my htaccess and that worked for me.

**Comment by shulard** [comment]
Hello @sarikas735,

Maybe we can help you 😄.
Can you give me more details about your current installation / configuration ?
What's your current setup ? Have you updated the .htaccess file / used the `allowed_http_origins` ?

**Comment by arrfonseca** [comment]
Hi @sarikas735 
In my case, the codes above have solved my issue but since I'm not a developer, after adding codes around I can't be sure what made it work. In any case, testing is also tricky, since Mautic works with cookies and identify you as a previous visitor you have always to wipe out browser cookies to any new testing. It will depend on how you build your workflow to do that.
