### ISSUE TITLE
GDPR support

### ISSUE THREAD

**Issue by hideokamoto** [mautic/mautic-wordpress#77]
Will you have any plan to support GDPR ?
The plugin added tracking code into WP site, so I think we should add feature to opt-in tracking .

**Comment by shulard** [comment]
You are totally right, we must support the "Don't track feature"... Since this extension only inject the script, we can listen on the DNT header and avoid loading script...

What do you think ?

**Comment by idea-2** [comment]
I rely on the https://github.com/AmauriC/tarteaucitron.js for the consent message. It also supports the DNT header.

**Comment by RCheesley** [comment]
Closing as this isn't an issue relating to the Mautic tracking itself but how it is implemented on the site

**Comment by shulard** [comment]
Currently there is no easy solution to be GDPR compliant using that extension. I agree that it’s not the extension work to handle all cases but adding some filters can help gaining more control. I’ll work on these changes ASAP.

**Comment by shulard** [comment]
Hello !

I've just opened a PR to add a new "script location" option. This new option will disallow the tracking script injection on page load.

If any of you can take a look at the code to review before merging it'll be really helpful ^^.

**Comment by shulard** [comment]
Hello here !

I've just published a new `v2.3.0` version. This version contains latest label update and the new `script_location` option for GDPR compliance.

I close this one which seems resolved. If you have an issue please open a new one !
