### ISSUE TITLE
No Data in Visitor Reports

### ISSUE THREAD

**Issue by lexul** [mautic/mautic-wordpress#8]
I have WP Mautic installed on an active site with no forms setup yet. The site is actively tracking anonymous leads (15k+) however when I run a report like "Visits published Pages", there are no stats. 

The following would be particularly helpful:
1.  Reporting time on site, page hits, referrals, most visited pages with WP Mautic
2.  Creating triggers from Wordpress pages within Mautic (user visited this page, going to send him this email). 

I can allocate up to 20 hours from my developers if someone can point me in the right direction with this.

**Comment by escopecz** [comment]
1) The pages reports in Mautic tracks mostly the internal Landing Pages. It'd be cool if your developers could prepare stats from tracking pixel hits as well. The Report Bundle is here:

https://github.com/mautic/mautic/tree/staging/app/bundles/ReportBundle

Any development is very welcome!

2) Triggers for specific URLs tracked by the Mautic Tracking Pixel are already part of Campaigns (Visits a page decision) and point action.

**Comment by shulard** [comment]
Hello @ghost,

I'm going to close that issue because it's an old one. If the issue still exists, please open a new one, we'll start a new discussion based on the latest Mautic updates.
