### ISSUE TITLE
Are there hooks to integrate custom forms with Mautic?

### ISSUE THREAD

**Issue by blue928** [mautic/mautic-wordpress#80]
I'm very new to Mautic and still wrapping my head around how to do integrations. I can't find any information online, so please point me to the right direction if any exists.

Is it possible to take form data on a Wordpress website and, after the custom form is submitted (not a mautic form) submit that data to mautic?

Here is very specifically what I'd like to do:

The WooCommerce checkout form is very standard - name, email address, address, etc. Theoretically, I would like to plug into one of the Woocommerce Checkout hooks and, upon successful checkout, submit the new customer details to my mautic installation (which is self hosted on a separate server) so they can continue as part of the drip campaign.

I can't imagine this is a new idea, so if there is any information out on how to do this, please provide references that could help out?

Thanks so much!

**Comment by shulard** [comment]
Hello,

Actually, you haven't any integration with Mautic API directly from the WordPress extension. We have #62 but I haven't found time to work on it actually...

The only solution for me is :
* Add API wrapper library in your project - https://github.com/mautic/api-library
* Check how to interact with the API - https://www.mautic.org/blog/developer/how-to-use-the-mautic-rest-api/
* Add API calls on the right hooks to push data to your Mautic instance.

It's a bit complex to implement but you must be able to do everything you need 😄.

**Comment by escopecz** [comment]
Maybe this may be handy:

https://medium.com/@jan_linhart/the-simplest-way-how-to-submit-a-form-data-to-mautic-1454d3afd005

But again. it's not related to this WP plugin.

**Comment by shulard** [comment]
I close this one since the solution is to implement the API manipulation.
