### ISSUE TITLE
Validation message not showing

### ISSUE THREAD

**Issue by taewookim** [mautic/mautic-wordpress#83]
WP: 4.9.8
Mautic: Latest (downloaded master.zip from github directly Sep 10, 2018)
Other plugins I should mention - i'm using on WP:
- Caching: WP Rocket
- WYSIWYG EDITOR: VisualBakery 

After a lengthy trial & error, i managed to get mautic setup along with nginx rewrite ... and I managed to embed mautic form on WP page, however..

https://s22.postimg.cc/ikypgyfip/image.png

Form validation doesn't seem to show up.

Any idea where Im going wrong?

**Comment by taewookim** [comment]
I noticed that WP mautic doesn't

1) pre-populate the cell with whatever was validated
2) for some reason, css is set to "display:none;"


This is hackish... temp fix, if anyone needs it.
you can use jquery to see if there is an error and  set display to "block".


in plugins/wp-mautic/shortcodes.php:

instead of 

	
```
	return '<script type="text/javascript" ' . sprintf(
		'src="%s/form/generate.js?id=%s"',
		esc_url( $base_url ),
		esc_attr( $atts['id'] )
	) . '></script>';

```	


return this

```

$scripts = [];
	$scripts[] =<<<JAVASCRIPT
<script type="text/javascript">
var getUrlParameter = function getUrlParameter(sParam) {
    var sPageURL = decodeURIComponent(window.location.search.substring(1)),
        sURLVariables = sPageURL.split('&'),
        sParameterName,
        i;

    for (i = 0; i < sURLVariables.length; i++) {
        sParameterName = sURLVariables[i].split('=');

        if (sParameterName[0] === sParam) {
            return sParameterName[1] === undefined ? true : sParameterName[1];
        }
    }
};
var $ = jQuery.noConflict();

$(document).ready( function() {
	var mauticError = getUrlParameter("mauticError");
	if(mauticError){
		$(".mauticform-errormsg").attr('style','display: block !important');
	}
});
</script>
JAVASCRIPT;

	$scripts[] = '<script type="text/javascript" ' . sprintf(
	'src="%s/form/generate.js?id=%s"',
		esc_url( $base_url ),
		esc_attr( $atts['id'] )
	) . '></script>';

```

**Comment by shulard** [comment]
Hello, 

This is very strange that the form validation message is `display: none`. Does it come from your website stylesheet or from the Mautic side ?

Your fix must works but it seems a bit hacky to be integrated in the plugin core...

**Comment by taewookim** [comment]
No.. i dont have any divs named "mauticform-errormsg"

**Comment by MajesteitBart** [comment]
Does it also change the url you are currently on? Because thats whats happening with me. 
domain.com/page changes to domain.com/page?mauticError=.....

- I'm on the most recent version 2.14.1
- It doesn't happen in "preview mode", validation messages show
- I'm using a subdomain, not a subdirectory

Is it some new bug?

**Comment by shulard** [comment]
@MajesteitBart, it's a strange behaviour... From my point of view it's another problem, what's the Mautic error returned here ? Do you have a JavaScript error in the console (be sure to activate "persist logs" to view them) ?

**Comment by Carlos-mb** [comment]
I guess I can update using "upgrade.php". 

For the future, Is there any way to see if are there new updates pending?

I have searched the web but I haven't found some way to check for updates. 

Thanks!

**Comment by shulard** [comment]
@Carlos-mb, currently there is a notification on the Mautic dashboard when there is a new update to install.

**Comment by Carlos-mb** [comment]
@shulard 

Thaks!

I asked because @MajesteitBart  said last version is 2.14.1 and I have 2.14.0 and there is no notificacion in dashboard.

**Comment by MajesteitBart** [comment]
> @MajesteitBart, it's a strange behaviour... From my point of view it's another problem, what's the Mautic error returned here ? Do you have a JavaScript error in the console (be sure to activate "persist logs" to view them) ?

Nope, doesn't seem to be any JS issues. Did a clean Bitnami instance just a minute ago on a different Subdomain and it's again showing this issue. 

The domain is https://bartvandermeeren.nl/. When you leave the e-mailfield empty, it will show the error.

**Comment by shulard** [comment]
Ok, I'll ask some help regarding that point :smile:

@escopecz, have you any idea here ? I don't understand how the submitted form can send without Ajax…

**Comment by escopecz** [comment]
The form is causing refresh. It should not do that for validation. But I don't see anything wrong. Maybe try it on a plain simple HTML page. Not your WP to rule out it's something with that combination.

**Comment by MajesteitBart** [comment]
This is weird, tried what you suggested using a manual copy on an html page. Same server, no problems there. Then I copied it manually to a WP page and it also gave no issues. 

@escopecz do you know what could be the issue then? Might it be related to the Mautic WP plugin?

**Comment by MajesteitBart** [comment]
Very weird, I tested it using a clean HTML page and manually copying the form to it: no problems. Then I manually copied it to a WP page, again it worked without problems. I now have two different pages with the same form, where one works and the other doesn't:

- Using WP Mautic shortcode: https://bartvandermeeren.nl/testmautic
- Using manual Mautic form: https://bartvandermeeren.nl/

Can it be a WP Mautic bug?

**Comment by reindje** [comment]
+1 Same problem...

**Comment by MajesteitBart** [comment]
@escopecz do you have an idea?

**Comment by seitzmichael** [comment]
We got the same issue with form validation while using the shortcode. Validation works fine if using the manual Mautic form.

**Comment by webgem-jpl** [comment]
Same problem here. Using the form in a basic html works fine. But on wordpress with mautic wordpress it trigger a page refresh and it doesnt show the error message. All errors message are on the page with display:"none".

**Comment by escopecz** [comment]
Can you guys test https://github.com/mautic/mautic/pull/6665 and https://github.com/mautic/mautic/pull/6645? Those should fix problems you are describing. If you test, please write your results to those PRs. It will help get them into the next release. Although the latter is merged already.

**Comment by cristianethiel** [comment]
Same problem here... _mauticform-errormsg_ not showing.. 
The page reloads and erros appear on URL but nothing on the page..
Any solution?

**Comment by shulard** [comment]
Hello @cristianethiel,

Can you give us more details ? Which version of Mautic are you using ?

**Comment by shulard** [comment]
Since this error is not directly related to the WP extension, I close this issue. I let the discussion open if it can helps others folks ^^
