### ISSUE TITLE
Forms not shown using .js but shown using "Manual Copy"

### ISSUE THREAD

**Issue by Carlos-mb** [mautic/mautic-wordpress#84]
I have had a form working for several weeks and now it as stopped working.

In the page source code now appears: <script type="text/javascript" src="https://mautic.coachingrealista.com/mautic/form/generate.js?id=3"></script>

And in the web appears nothing. 

I works fine if I use the "Manual copy" option and I add script and html manually.

**Comment by shulard** [comment]
Hello,

Is your website address `coachingrealista.com` ?

I just checked on the website in browser developer console and it seems to have different errors regarding access control policy. It also seems that you have the tracker image and the tracker script included in each page.

Have you allowed your website to communicate with your Mautic instance (in your mautic config : https://mautic.com/help/getting-started-mautic-cloud/#5) ?

Can you give me the URL where the form is embedded ?

**Comment by Carlos-mb** [comment]
Hi

Yes, thats my site. 

First of all I want to thank you your effort. 

The plugin was working fine and it stoped working without report any error. 

It should be great if you tell me what should I do with access contron polocy, image and tracking code

Anyway, I have allowed the domain to comunicate with Mautic right now. 

The page where the form is is: https://coachingrealista.com/el-metodo-de-coaching-realista

It's working because I have replaced the shotcode with the Html of the form. 

For testing propuses, at the end of the page I have added this 

> -[mautic type="form" id="3"]-


The result is "- -" at the very bottom of the page. 

When it works again, I'll be able to see the form.

**Comment by shulard** [comment]
I rechecked and the mautic event errors regarding the CORS have disappeared, it's a first step forward.

About the form I really don't understand what's happening. On my own Mautic instance when I access the form script the script is displayed in the browser, for example:  https://mautic.chstudio.fr/form/generate.js?id=1

On your website I get an empty response when I try to load the script: https://mautic.coachingrealista.com/mautic/form/generate.js?id=3

Which version of Mautic are you using ? Which version of PHP ?

**Comment by Carlos-mb** [comment]
May be a rights problem?

**Comment by Carlos-mb** [comment]
Mautic 2.14.1
PHP Version 7.0.32

**Comment by shulard** [comment]
Hello @Carlos-mb,

I've checked on my side and can't find a way to reproduce the error. Currently I'm using the shortcode on my website without any trouble : https://chstudio.fr/un-magazine-en-francais-sur-php-et-son-ecosysteme/

**Comment by shulard** [comment]
I've opened an issue on the Mautic repo to keep track of the Cachewall problem : mautic/mautic#6817

I close this one which is now resolved.
