### ISSUE TITLE
Add Woocomerce support

### ISSUE THREAD

**Issue by vgpastor** [mautic/mautic-wordpress#97]
Integrate the possibilitie that users that buy in the Woocomerce store are integrated into Mautic instance

**Comment by shulard** [comment]
Hello,

Can you elaborate a bit more ? You want to send custom information inside the Mautic tracker based on the WooCommerce store details ?

If it's your needs, you can already do something with the current plugin :

```php
<?php

add_filter('wpmautic_tracking_attributes', function(array $attributes) {
    // Here you can add new fields to be sent to Mautic
    // Execute some logic to retrieve those specific data
    $attributes['woo-username'] = $wooName;
    $attributes['woo-bought-product-id'] = $wooProduct->id;

    return $attributes;
});
```

**Comment by vgpastor** [comment]
Hi @shulard 

No, I propose that, when an user buy a aproduct inside de store, we can send the information about the customer to mautic, including diferentes fields, how the total amount or any other parameters the we like, for example:
I have a store that sell software an hardware, i think that it's a nice idea that can store in mautic in a specific segment for type of equipemnt[software, hardware] and inlcude a tag with the brand  for example and add any points based in the price for example.

if you guide me, in the events in the plugin or the possibilities i can try to develop this upgrade,

Regards!

**Comment by 1DayWebs** [comment]
Check out Mauticommerce plugin ... it does what you need

**Comment by shulard** [comment]
Thank you @1DayWebs for the info. I add the plugin link for reference : https://wordpress.org/plugins/Mauticommerce/

It doesn't seems to be maintained anymore but it does the job. I close this issue since a solution already exists.
